services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  tile38:
    image: tile38/tile38
    ports:
      - "9851:9851"
    depends_on:
      - redis

  backend:
    build: ./buygo-backend
    ports:
      - "8080:8080"
      - "6060:6060"
      - "2112:2112"
    depends_on:
      - redis
      - tile38
    environment:
      - REDIS_URL=redis:6379
      - TILE38_URL=tile38:9851

  frontend:
    build: ./buygo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - default

  presentation:
    build:
      context: ./slides
    container_name: buygo-presentation
    ports:
      - "8089:80"
    restart: unless-stopped

volumes:
  redis-data:
