services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  tile38:
    image: tile38/tile38
    ports:
      - "9851:9851"
    depends_on:
      - redis

  backend:
    build: ./buygo-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - tile38
    environment:
      - REDIS_URL=redis:6379
      - TILE38_URL=tile38:9851

  frontend:
    build: ./buygo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  redis-data:
