package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"buygo/graph/model"
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// CreateDeal is the resolver for the createDeal field.

func (r *mutationResolver) CreateDeal(ctx context.Context, input model.DealInput) (*model.Deal, error) {
	now := time.Now()

	deal := &model.Deal{
		ID:                 uuid.NewString(),
		Title:              input.Title,
		Description:        input.Description,
		VendorID:           input.VendorID,
		Price:              input.Price,
		OriginalPrice:      input.OriginalPrice,
		DiscountPercentage: calculateDiscount(input.Price, input.OriginalPrice),
		Location: &model.GeoPoint{
			Latitude:  input.Location.Latitude,
			Longitude: input.Location.Longitude,
		},
		CreatedAt: now,
		ExpiresAt: input.ExpiresAt,
	}

	r.mu.Lock()
	r.Deals = append(r.Deals, deal)
	r.mu.Unlock()

	err := r.Tile.Keys.Set("deals", deal.ID).
	Point(deal.Location.Latitude, deal.Location.Longitude).
	Field("created_at", float64(deal.CreatedAt.Unix())).
	Do(ctx)

	if err != nil {
		return nil, fmt.Errorf("tile38 insert failed: %w", err)
	}

	return deal, nil
}

func calculateDiscount(price float64, original *float64) *float64 {
	if original == nil || *original == 0 {
		return nil
	}
	discount := (1 - (price / *original)) * 100
	return &discount
}

// DealsInViewport is the resolver for the dealsInViewport field.
func (r *queryResolver) DealsInViewport(ctx context.Context, bb model.BoundingBox) ([]*model.Deal, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	var matches []*model.Deal
	for _, d := range r.Deals {
		lat := d.Location.Latitude
		lon := d.Location.Longitude
		if lat >= bb.MinLatitude && lat <= bb.MaxLatitude && lon >= bb.MinLongitude && lon <= bb.MaxLongitude {
			matches = append(matches, d)
		}
	}
	return matches, nil
}

// DealCreatedInViewport is the resolver for the dealCreatedInViewport field.
func (r *subscriptionResolver) DealCreatedInViewport(ctx context.Context, boundingBox model.BoundingBox) (<-chan *model.Deal, error) {
	panic(fmt.Errorf("not implemented: DealCreatedInViewport - dealCreatedInViewport"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
